import json

SYSTEM_PROMPT = """
You are a senior Retrieval-Augmented Generation (RAG) evaluation engineer.

You are analyzing a benchmark performed across one or more RAG pipeline configurations.

You will receive:

- Benchmark metrics
- Aggregated benchmark statistics
- Structured deterministic findings generated by the analysis engine

Your responsibility is to explain what the benchmark demonstrates.

Important:

- Treat the deterministic findings as facts.
- Interpret the supplied metadata rather than inventing explanations.
- Do not recommend pipeline changes.
- Do not prescribe experiments.
- Do not invent benchmark results.
- Do not mention information that was not provided.

Focus on:

- notable strengths
- notable weaknesses
- engineering observations
- important tradeoffs
- overall benchmark takeaway

Return ONLY valid JSON.

{
  "executive_insight": "string",

  "strengths": [
    "string"
  ],

  "weaknesses": [
    "string"
  ],

  "engineering_observations": [
    "string"
  ],

  "benchmark_takeaway": "string"
}
"""


def build_insight_prompt(
    results,
    findings,
    aggregated,
):
    prompt = {
        "benchmark_results": [
            {
                "configuration": r.config_name,
                "grounding": round(r.semantic_grounding, 4),
                "faithfulness": round(r.faithfulness, 4),
                "coverage": round(r.semantic_query_coverage, 4),
                "retrieval_quality": round(
                    r.retrieval_quality_score,
                    4,
                ),
                "latency_ms": round(r.latency, 2),
                "grounded_rate": round(r.grounded_rate, 4),
                "abstain_rate": round(r.abstain_rate, 4),
            }
            for r in results
        ],
        "benchmark_summary": {
            "averages": aggregated["averages"],
            "ranges": aggregated["ranges"],
        },
        "findings": [
            {
                "category": f.category,
                "title": f.title,
                "configuration": f.configuration,
                "metadata": f.metadata,
            }
            for f in findings
        ],
    }

    return json.dumps(prompt)
